[package]
name = "cryptography"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ec = "0.4.2"
ark-ff = "0.4.2"
ark-std = "0.4.0"
num-bigint = {version = "0.4.6", features=["rand"]}
num-integer = "0.1.46"
num-rational = "0.4.2"
num-traits = "0.2.19"
rand = "0.8.5"
